fix: TS build errors
This commit fixes 2 errors that were caused when running 'tsc':

1. lib/yaml-parser/index.ts:15:46 - error TS2349: This expression is not callable.
  .... has signatures, but none of those signatures are compatible with each other.

2. return YAML.parseAllDocuments(fileContent).map((doc) => {
                                              ~~~
lib/yaml-parser/index.ts:15:51 - error TS7006: Parameter 'doc' implicitly has an 'any' type.

doc.toJSON() returns 'any' so that's something we can not change. However, we can cast the parseAllDocuments() result to the expected type YAML.Document.Parsed<YAML.ParsedNode>[]. Then map won't complain about incompatibility of signatures.